name: Trigger Second Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN_MM }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: "mmaksimovic94",
              repo: "mm-test",
              workflow_id: 'dispatched_workflow.yml',
              ref: 'mm-test-checks',
              # inputs: {
              #   original_pr_number: "${{ github.event.pull_request.number }}",
              #   head_sha: "${{ github.event.pull_request.head.sha }}"
              # }
            })
