name: Trigger Second Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Workflow with curl
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer <YOUR-TOKEN>"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/mmaksimovic94/mm-test/actions/workflows/dispatched_workflow.yml/dispatches \
          -d '{"ref":"mm-test-checks"}'

      # - name: Trigger Workflow
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.GH_TOKEN_MM }}
      #     script: |
      #       github.rest.actions.createWorkflowDispatch({
      #         owner: "mmaksimovic94",
      #         repo: "mm-test",
      #         workflow_id: "dispatched_workflow.yml",
      #         ref: "mm-test-checks"
      #       })
