name: Test exit

on:
  workflow_dispatch:

jobs:
  test-exit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Testing exit
        run: exit 0